Fix COPY FROM STDIN handling
pgbouncer/pgbouncer pull request #1025
Opened 2024-02-16 11:42 UTC by JelteF

In #854 full tracking of expected responses was implemented. This turned out this have bugs when sending `COPY FROM STDIN` queries using the extended protocol. The protocol explicitely allows sending `Sync` messages after sending an `Execute` message for a `COPY FROM STDIN` command. Such Sync messages are ignored by the server until a CopyDone or CopyFail message is received. The new command queue tracking did not take this into account, and was incorrectly expecting more ReadyForQuery messages from the server.

This PR fixes that issue. It also removes the rfq_count tracking, since it's now only keeping track of a strict subset of what the outstanding request queue was tracking.

Fixes #1023
Fixes #1024

TODO:
- [ ] Add tests for COPY TO STDOUT

2024-02-21 12:56 UTC, JelteF commented on src/server.c
>  			server->query_failed = true;
This should happen always probably, otherwise we won't pop a later received CopyDone message in case of failure.

2024-02-21 18:47 UTC, eulerto requested changes
LGTM. Don't forget to include test_copy.py into EXTRA_DIST target (I submitted another PR #1026 that included some recent tests into it.)

2024-02-21 18:47 UTC, eulerto commented on test/conftest.py
> +
Rename table "t" to "test_copy". It seems clear that it is used by `test_copy.py`.

2024-02-22 12:03 UTC, eulerto commented
There are some tests that still refers to table "t".

2024-02-22 12:25 UTC, eulerto approved these changes
LGTM

2024-02-22 12:41 UTC, merged