Add error message on reload fail
pgbouncer/pgbouncer pull request #1231
Opened 2024-12-23 05:22 UTC by AndrewJackson2020

This PR adds an error message to the reload command on the admin console if there is a failure. Currently the only way to know if the admin command worked is to have the logs open while you enter `RELOAD` on the admin screen. If you do not you might miss the fact that your configuration change failed. The purpose of this PR is to make the failed reload more obvious. Even if the entire message will not be displayed in the admin console it will at least tell the user that something went wrong so they can look at the logs.

2024-12-23 12:29 UTC, JelteF requested changes
Overall, a good improvement I think. Tests need to be updated accordingly though, because now some RELOADs have started failing in the tests.

2024-12-23 14:25 UTC, AndrewJackson2020 commented on src/admin.c
> +		return admin_error(admin, "RELOAD failed, see logs for additional details");
Okay just updated to invoke `send_pooler_error` directly. Specifically it now raises a warning `01000`. Happy to change this if there is something more appropriate.

Also the unit tests should be fixed now.

2025-01-16 04:31 UTC, AndrewJackson2020 commented
@JelteF Seeing failures in a number of tests that used to work, even when running cirrus pipeline locally on master. Did something change with the CI environment?

2025-01-19 22:20 UTC, AndrewJackson2020 commented
Added a test to this PR. Seeing a failure in a known flakey test, everything else looks good.

2025-03-13 01:16 UTC, JelteF commented on src/admin.c
> +		return send_pooler_error(admin, true, "01000", false, "RELOAD failed, see logs for additional details");
I think F0000, i.e. config_file_error is a better error code.
```suggestion
		return send_pooler_error(admin, true, "F0000", false, "RELOAD failed, see logs for additional details");
```

2025-03-16 16:50 UTC, JelteF commented on test/test_admin.py
> +            psycopg.errors.DatabaseError,
Let's check for the actual error code here too by using a more specific exception class.

2025-03-16 20:31 UTC, AndrewJackson2020 commented on test/test_admin.py
> +            psycopg.errors.DatabaseError,
Agreed. Will fix this later today.

2025-03-17 02:37 UTC, AndrewJackson2020 commented on test/test_admin.py
> +            psycopg.errors.DatabaseError,
Changed this to specifically test for `psycopg.errors.ConfigFileError`.

2025-04-16 20:20 UTC, JelteF approved these changes

2025-04-16 20:20 UTC, JelteF commented
Needs a rebase, but other than that this looks good.

2025-04-16 21:37 UTC, AndrewJackson2020 commented
Just rebased to rerun the tests and the aforementioned valgrind test passed this time. Pretty sure its a preexisting flaky test. Everything is green now.

2025-04-16 22:08 UTC, merged