feat: introduce support for the `auth_dbname` option
pgbouncer/pgbouncer pull request #645
Opened 2021-10-06 12:46 UTC by gbartolini

Introduce a global or database-specific option (specified in the
connection parameters string) called `auth_dbname` which points
to the name of a database defined in the `[databases]` section
to be reserved for authentication purposes.

If required, the `auth_query` will be run against this database.

By default it is not set. It requires that `auth_user` is set.

Signed-off-by: Gabriele Bartolini <gabriele.bartolini@enterprisedb.com>
Signed-off-by: Leonardo Cecchi <leonardo.cecchi@enterprisedb.com>

2021-11-16 09:27 UTC, 3nprob commented
Would be great to get this moving. I think many others have been running with self-built binaries with the existing #315 (which seems to have been blocked due to missing configuratIion)

2022-08-11 23:01 UTC, JelteF commented
Needs a rebase before this can be considered. Also valgrind seems to have failed for the old code. The feature itself seems useful, mostly so you don't need to define the `SECURITY DEFINER` function in each postgres database.

2022-08-12 08:12 UTC, JelteF requested changes
needs a rebase and valgrind fixes

2022-09-01 21:48 UTC, alvherre-edb commented
There's large community demand for this feature, as seen here: https://github.com/pgbouncer/pgbouncer/pull/315  Please merge it soon.

2022-09-02 07:12 UTC, JelteF commented
Both me and and @eulerto left reviews on this PR without addressing those, this cannot be merged.

If you want this feature feel free to make these changes (possibly in a new PR if the original author does not have time).

2022-10-08 11:50 UTC, goksgie commented
Implemented here: https://github.com/pgbouncer/pgbouncer/pull/764

2023-01-10 19:38 UTC, eulerto commented
Refer to #764 .

2023-01-10 19:38 UTC, closed without merging