Track connection waiting for password in a pool
pgbouncer/pgbouncer pull request #734
Opened 2022-06-29 07:40 UTC by janchochol

After receiving `PKT_STARTUP` packet, client is associated to database
(result of `find_database` is stored in `client->db`).

For some authentication mechanisms (like plain or MD5), pgbouncer is
waiting for password packet, before it switches client to `CL_ACTIVE`
state).

If there is enough delay between these two packets, it can happen that
`do_full_maint` is called.
These clients are not linked anywhere in pool, so it can happen that
auto database can be marked as inactive.

When password packet arrives, there is no mechanism to un-mark such
database as inactive (in case of no new connections), so it can be
later killed leading to errors like:

```
Jun 27 08:46:13 node001 pgbouncer[16819]: C-0x115b218: db_001/user01@10.1.1.1:43132 pooler error: database removed severity=warning
```

Even worse is situation, when password packet arrives after
`autodb_idle_timeout`, which leads to use-after-free situation (as used
database is free). Fortunately this is not probable, as
`autodb_idle_timeout` is generally larger that delay between first two
packets.

This fix ensures, that after `PKT_STARTUP` client connection is tracked
in a pool for all cases (base on code analysis, this seemd as last place).

2022-06-29 07:42 UTC, janchochol commented
I am not sure, if proposed way is correct fix.

As we are periodically hit by this issue in the production, we are prepared to change used approach upon request.

2022-06-29 07:43 UTC, janchochol commented
This should also fix https://github.com/pgbouncer/pgbouncer/issues/288, as we had more time for analysis this time.

2022-08-11 14:04 UTC, JelteF commented
Do you think there's a way to create a test for the issue you're describing?

2022-09-06 11:16 UTC, JelteF requested changes
Would be good to have a regression test for this issue included in the PR. Also many existing tests are failing so this code likely has a bug somewhere.

2022-09-06 11:31 UTC, janchochol commented
Sorry for late response, but we unfortunately have currently other priorities.
We will definitely investigate how to add some regression tests.

2023-02-13 14:49 UTC, JelteF commented
Writing regression tests should be a lot simpler now. Because the framework is now using python. Another thing I realised is that this new client type should probably also be made visible by `SHOW CLIENTS` in admin.c

2024-12-02 22:50 UTC, JelteF commented
@janchochol are you intending to finish this?

2026-08-28 18:16 UTC, eulerto commented
Closed due to inactivity.

2026-08-28 18:16 UTC, closed without merging