Delete all prepared statements if DEALLOCATE ALL command was executed
pgbouncer/pgbouncer pull request #972
Opened 2023-10-27 07:58 UTC by knizhnik

This small bug quite ugly fix is trying to solve the problem with DEALLOCATE ALL explained here:

https://github.com/prisma/prisma/issues/21635

2023-10-27 10:00 UTC, JelteF requested changes
I think supporting DEALLOCATE ALL is a worthy effort. It currently silently breaks the whole server. And because there is no protocol level equivalent, all clients that want send this need to send it as SQL.

When I saw the title of this PR I thought I was going to hate it, because I'd expect it to implement a very simple query parser. And I was happily surprised that's not what's going on. Instead it's using the command tag from the CommandComplete packet. And I actually think that idea is quite elegant, since the command tags are well defined by postgres and easy to parse (as opposed to SQL which can have comments or extra spaces or lowercase). So I quite like this general approach. I left some comments on changes that should be done to make this handle some more edge cases.

Also this needs some tests. And docs need to be updated that we now actually do support DEALLOCATE ALL

2023-10-30 11:34 UTC, janpio commented
I have just opened https://github.com/pgbouncer/pgbouncer/issues/974, which explains the problem and thus motivation behind such a change a bit more. Great to see there is already a PR aiming to fix this problem! 💚

2023-10-31 17:24 UTC, knizhnik commented on src/server.c
> +			if (mbuf_get_string(&pkt->data, &tag)) {
Done

2023-10-31 17:27 UTC, knizhnik commented on src/server.c
> +					free_server_prepared_statements(server);
Done

2023-10-31 17:37 UTC, knizhnik commented on src/server.c
> +				if (strcmp(tag, "DEALLOCATE ALL") == 0)	{
Done

2023-10-31 22:10 UTC, JelteF requested changes
Code looks good. All it now needs is a test.

2023-10-31 22:10 UTC, JelteF commented on src/server.c
> +					strcmp(tag, "DISCARD ALL") == 0)
We should have a test for both of these

2023-10-31 22:10 UTC, JelteF commented on lib
You seem to have accidentally changed (rolled back?) some changes to the libusual submodule. Can you undo those?

2023-10-31 22:14 UTC, JelteF commented
Also CI is complaining about the codeformatting. `make format` should fix that.

2023-11-01 08:14 UTC, knizhnik commented on lib
Sorry, fixed

2023-11-01 08:14 UTC, knizhnik commented on src/server.c
> +					strcmp(tag, "DISCARD ALL") == 0)
Added

2023-11-01 09:46 UTC, JelteF approved these changes

2023-11-01 13:34 UTC, merged

2023-11-02 14:16 UTC, JelteF commented
> How might this affect non-PostgreSQL uses of PgBouncer.

To be clear, you're talking about other databases that use the Postgres protocol, but don't speak Postgres its SQL dialect, right? If so, then tl;dr I think the impact would be negligable. 

The "CommandComplete parsing" here would only have any impact in practice if the server responded with `DISCARD ALL`/`DEALLOCATE ALL` to a query. While not a strict requirement [the protocol description of the CommandComplete packet][1] indicates that this really only should be done when a `DEALLOCATE ALL`/`DISCARD ALL` query was sent.
> The command tag. This is usually a single word that identifies which SQL command was completed. 

While in theory it's possible that some other non-PostgreSQL server implements a `DEALLOCATE ALL`/`DISCARD ALL` command with different semantics than Postgres, it seems rather unlikely that in practice such different semantics would not include clearing of the prepared statements. Especially because there's no protocol level message that can be used for the purpose of clearing all prepared statements. So in practice I don't think this would impact anyone badly. 

[1]: https://www.postgresql.org/docs/current/protocol-message-formats.html#PROTOCOL-MESSAGE-FORMATS-COMMANDCOMPLETE